package capoci

import (
	"context"

	capiv1alpha1 "github.com/openshift/oci-capi-operator/api/v1alpha1"
	"github.com/openshift/oci-capi-operator/internal/components"
	"github.com/openshift/oci-capi-operator/internal/utils"
	"k8s.io/apimachinery/pkg/apis/meta/v1/unstructured"
	"sigs.k8s.io/cluster-api/cmd/clusterctl/api/v1alpha3"

	corev1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
	"sigs.k8s.io/controller-runtime/pkg/client"
	"sigs.k8s.io/controller-runtime/pkg/controller/controllerutil"
)

type CAPOCICredentials struct {
	TenancyID            string `envconfig:"OCI_TENANCY_ID"`
	UserID               string `envconfig:"OCI_USER_ID"`
	Region               string `envconfig:"OCI_REGION"`
	Fingerprint          string `envconfig:"OCI_CREDENTIALS_FINGERPRINT"`
	PrivateKey           string `envconfig:"OCI_CREDENTIALS_KEY"`
	UseInstancePrincipal string `envconfig:"OCI_USE_INSTANCE_PRINCIPAL" default:"false"`
	Passphrase           string `envconfig:"OCI_CREDENTIALS_PASSPHRASE" default:""`
}

// GetClusterctlComponents returns a list of components for the CAPOCI controller manager
// generated by clusterctl
func GetClusterctlComponents(ctx context.Context, deploymentName string, serviceAccountName string, capociNamespace string, autoscaler *capiv1alpha1.OCIClusterAutoscaler, webhookServiceName string, scheme *runtime.Scheme) ([]unstructured.Unstructured, error) {
	components, err := utils.GenerateCAPIComponents(ctx, "oci", v1alpha3.InfrastructureProviderType, capociNamespace)
	if err != nil {
		return nil, err
	}
	reconcileComponents := []unstructured.Unstructured{}
	for _, component := range components {
		utils.SetDefaultLabels(&component, autoscaler.Name)
		switch component.GetKind() {
		case "Service":
			utils.SetOpenshiftServiceCertAnnotation(&component, webhookServiceName)
			reconcileComponents = append(reconcileComponents, component)
		case "ValidatingWebhookConfiguration", "MutatingWebhookConfiguration":
			utils.SetOpenshiftCABundleAnnotation(&component)
			reconcileComponents = append(reconcileComponents, component)
		case "Deployment":
			utils.EditDeploymentCerts(scheme, &component, webhookServiceName)
			component.SetName(deploymentName)
			reconcileComponents = append(reconcileComponents, component)
		case "ServiceAccount":
			component.SetName(serviceAccountName)
			reconcileComponents = append(reconcileComponents, component)
		case "Certificate", "Issuer", "Namespace", "Secret", "CustomResourceDefinition": // skip these
		default:
			reconcileComponents = append(reconcileComponents, component)
		}
	}
	return reconcileComponents, nil
}

func GetComponents(capociNamespace string, instance *capiv1alpha1.OCIClusterAutoscaler, auth *CAPOCICredentials) *components.Component {
	namespace, namespaceMutateFn := Namespace(capociNamespace, instance)
	authConfigSecret, authConfigSecretMutateFn := AuthConfigSecret(instance, capociNamespace, auth)
	return &components.Component{
		Name: "CAPOCI",
		Subcomponents: components.SubcomponentList{
			{Name: "namespace", Object: namespace, MutateFn: namespaceMutateFn},
			{Name: "authConfigSecret", Object: authConfigSecret, MutateFn: authConfigSecretMutateFn},
		},
	}
}

func Namespace(capociNamespace string, autoscaler *capiv1alpha1.OCIClusterAutoscaler) (client.Object, controllerutil.MutateFn) {
	namespace := &corev1.Namespace{
		ObjectMeta: metav1.ObjectMeta{
			Name: capociNamespace,
		},
	}
	mutateFn := func() error {
		utils.SetDefaultLabels(namespace, autoscaler.Name)
		return nil
	}
	return namespace, mutateFn
}

func AuthConfigSecret(autoscaler *capiv1alpha1.OCIClusterAutoscaler, capociNamespace string, auth *CAPOCICredentials) (client.Object, controllerutil.MutateFn) {
	secret := &corev1.Secret{
		ObjectMeta: metav1.ObjectMeta{
			Name:      "capoci-auth-config",
			Namespace: capociNamespace,
		},
	}

	mutateFn := func() error {
		utils.SetDefaultLabels(secret, autoscaler.Name)
		secret.Data = map[string][]byte{
			"tenancy":              []byte(auth.TenancyID),
			"user":                 []byte(auth.UserID),
			"region":               []byte(auth.Region),
			"fingerprint":          []byte(auth.Fingerprint),
			"key":                  []byte(auth.PrivateKey),
			"useInstancePrincipal": []byte(auth.UseInstancePrincipal),
			"passphrase":           []byte(auth.Passphrase),
		}
		return nil
	}
	return secret, mutateFn
}
