package capi

import (
	"context"
	"fmt"

	capiv1alpha1 "github.com/openshift/oci-capi-operator/api/v1alpha1"
	"github.com/openshift/oci-capi-operator/internal/components"
	"github.com/openshift/oci-capi-operator/internal/utils"
	"k8s.io/apimachinery/pkg/apis/meta/v1/unstructured"

	securityv1 "github.com/openshift/api/security/v1"
	corev1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
	"sigs.k8s.io/controller-runtime/pkg/client"
	"sigs.k8s.io/controller-runtime/pkg/controller/controllerutil"

	v1alpha3 "sigs.k8s.io/cluster-api/cmd/clusterctl/api/v1alpha3"
)

// GetClusterctlComponents returns a Component for the CAPI controller manager
// generated by clusterctl
func GetClusterctlComponents(ctx context.Context, deploymentName string, serviceAccountName string, capiSystemNamespace string, autoscaler *capiv1alpha1.OCIClusterAutoscaler, webhookServiceName string, scheme *runtime.Scheme) ([]unstructured.Unstructured, error) {
	components, err := utils.GenerateCAPIComponents(ctx, "cluster-api", v1alpha3.CoreProviderType, capiSystemNamespace)
	if err != nil {
		return nil, err
	}
	reconcileComponents := []unstructured.Unstructured{}

	for _, component := range components {
		utils.SetControllerLabels(&component, autoscaler.Name)
		switch component.GetKind() {
		case "Service":
			utils.SetOpenshiftServiceCertAnnotation(&component, webhookServiceName)
			reconcileComponents = append(reconcileComponents, component)
		case "ValidatingWebhookConfiguration", "MutatingWebhookConfiguration":
			utils.SetOpenshiftCABundleAnnotation(&component)
			reconcileComponents = append(reconcileComponents, component)
		case "Deployment":
			utils.EditDeploymentCerts(scheme, &component, webhookServiceName)
			component.SetName(deploymentName)
			reconcileComponents = append(reconcileComponents, component)
		case "ServiceAccount":
			utils.SetDefaultLabels(&component, autoscaler.Name)
			component.SetName(serviceAccountName)
			reconcileComponents = append(reconcileComponents, component)
		case "Certificate", "Issuer", "Namespace", "Secret", "CustomResourceDefinition": // skip these
		default:
			reconcileComponents = append(reconcileComponents, component)
		}
	}
	return reconcileComponents, nil
}

func GetComponents(capiSystemNamespace, capociSystemNamespace, capiServiceAccountName, capociServiceAccountName string, instance *capiv1alpha1.OCIClusterAutoscaler) *components.Component {
	capiSCC, capiSCCMutateFn := SecurityContextConstraints(capiSystemNamespace, capociSystemNamespace, capociServiceAccountName, capiServiceAccountName, instance)
	namespace, namespaceMutateFn := CAPINamespace(capiSystemNamespace, instance)
	return &components.Component{
		Name: "CAPI",
		Subcomponents: components.SubcomponentList{
			{Name: "scc", Object: capiSCC, MutateFn: capiSCCMutateFn},
			{Name: "namespace", Object: namespace, MutateFn: namespaceMutateFn},
		},
	}
}

func CAPINamespace(capiSystemNamespace string, instance *capiv1alpha1.OCIClusterAutoscaler) (client.Object, controllerutil.MutateFn) {
	namespace := &corev1.Namespace{
		ObjectMeta: metav1.ObjectMeta{
			Name: capiSystemNamespace,
		},
	}
	mutateFn := func() error {
		utils.SetDefaultLabels(namespace, instance.Name)
		return nil
	}
	return namespace, mutateFn
}

// SecurityContextConstraints defines the SCC for the CAPI manager and CAPOCI controller manager
func SecurityContextConstraints(capiSystemNamespace string, capociSystemNamespace string, capociServiceAccountName string, capiServiceAccountName string, instance *capiv1alpha1.OCIClusterAutoscaler) (client.Object, controllerutil.MutateFn) {
	scc := &securityv1.SecurityContextConstraints{
		ObjectMeta: metav1.ObjectMeta{
			Name: "oci-capi",
		},
	}

	mutateFn := func() error {
		scc.RunAsUser = securityv1.RunAsUserStrategyOptions{
			Type: securityv1.RunAsUserStrategyRunAsAny,
		}
		scc.SELinuxContext = securityv1.SELinuxContextStrategyOptions{
			Type: securityv1.SELinuxStrategyRunAsAny,
		}
		scc.SeccompProfiles = []string{"runtime/default"}
		scc.Users = []string{
			fmt.Sprintf("system:serviceaccount:%s:%s", capociSystemNamespace, capociServiceAccountName),
			fmt.Sprintf("system:serviceaccount:%s:%s", capiSystemNamespace, capiServiceAccountName),
		}
		utils.SetDefaultLabels(scc, instance.Name)
		return nil
	}

	return scc, mutateFn
}
